// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3SnotGuIg7WR1M3og0-KXlCgYH3P1FY',
    appId: '1:567215995094:web:090c41092dca82143bf177',
    messagingSenderId: '567215995094',
    projectId: 'gp-4-prj',
    authDomain: 'gp-4-prj.firebaseapp.com',
    storageBucket: 'gp-4-prj.firebasestorage.app',
    measurementId: 'G-Q2XZQDDNN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uAv752ejERlmf7CzdMiDKu7hQvQ0tf4',
    appId: '1:567215995094:android:562e1774e78f656b3bf177',
    messagingSenderId: '567215995094',
    projectId: 'gp-4-prj',
    storageBucket: 'gp-4-prj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-iepk76TQeUIjTgbGb-RsnfyGbl2b2XA',
    appId: '1:567215995094:ios:1df0b53b4ab695173bf177',
    messagingSenderId: '567215995094',
    projectId: 'gp-4-prj',
    storageBucket: 'gp-4-prj.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-iepk76TQeUIjTgbGb-RsnfyGbl2b2XA',
    appId: '1:567215995094:ios:e3eb4d746a31ff983bf177',
    messagingSenderId: '567215995094',
    projectId: 'gp-4-prj',
    storageBucket: 'gp-4-prj.firebasestorage.app',
    iosBundleId: 'com.example.teamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy3SnotGuIg7WR1M3og0-KXlCgYH3P1FY',
    appId: '1:567215995094:web:d5bb739cda3622893bf177',
    messagingSenderId: '567215995094',
    projectId: 'gp-4-prj',
    authDomain: 'gp-4-prj.firebaseapp.com',
    storageBucket: 'gp-4-prj.firebasestorage.app',
    measurementId: 'G-NWC55R5NJK',
  );
}
